name: laab2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/photo1.png
    - assets/foto2.png
    - assets/foto3.jpeg
    - assets/foto4.jpeg
    - assets/foto5.jpeg
    - assets/foto6.jpeg
    - assets/foto7.jpeg
    - assets/photop.jpg
    - assets/foto9.jpeg
